"""initial

Revision ID: 2acb3a08baaf
Revises: 
Create Date: 2026-04-28 09:38:23.294910
"""
from alembic import op
import sqlalchemy as sa


revision = '2acb3a08baaf'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advertisers',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('vertical', sa.String(length=32), nullable=False),
    sa.Column('vertical_source', sa.String(length=16), nullable=False),
    sa.Column('vertical_classified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain')
    )
    op.create_table('digest_runs',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('ran_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('top_advertisers_json', sa.Text(), nullable=False),
    sa.Column('telegram_message_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('publishers',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('seed_email_address', sa.String(length=320), nullable=False),
    sa.Column('subscribed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_email_received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain'),
    sa.UniqueConstraint('seed_email_address')
    )
    op.create_table('creatives',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('advertiser_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('creative_hash', sa.String(length=64), nullable=False),
    sa.Column('headline', sa.Text(), nullable=True),
    sa.Column('screenshot_path', sa.Text(), nullable=False),
    sa.Column('click_tracker_url', sa.Text(), nullable=False),
    sa.Column('final_landing_url', sa.Text(), nullable=True),
    sa.Column('final_landing_url_resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['advertiser_id'], ['advertisers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('creative_hash')
    )
    op.create_table('emails_raw',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('publisher_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('imap_uid', sa.BigInteger(), nullable=False),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('from_addr', sa.String(length=320), nullable=True),
    sa.Column('raw_html_path', sa.Text(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['publisher_id'], ['publishers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('publisher_id', 'imap_uid', name='uq_emails_publisher_uid')
    )
    op.create_index('ix_emails_publisher_received', 'emails_raw', ['publisher_id', 'received_at'], unique=False)
    op.create_table('impressions',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('creative_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('publisher_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('email_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creative_id'], ['creatives.id'], ),
    sa.ForeignKeyConstraint(['email_id'], ['emails_raw.id'], ),
    sa.ForeignKeyConstraint(['publisher_id'], ['publishers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_impressions_creative_seen', 'impressions', ['creative_id', 'seen_at'], unique=False)
    op.create_index('ix_impressions_publisher_seen', 'impressions', ['publisher_id', 'seen_at'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_impressions_publisher_seen', table_name='impressions')
    op.drop_index('ix_impressions_creative_seen', table_name='impressions')
    op.drop_table('impressions')
    op.drop_index('ix_emails_publisher_received', table_name='emails_raw')
    op.drop_table('emails_raw')
    op.drop_table('creatives')
    op.drop_table('publishers')
    op.drop_table('digest_runs')
    op.drop_table('advertisers')
    # ### end Alembic commands ###
